---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: trading
    service: chat
  name: chat
  namespace: $NAMESPACE
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trading
      service: chat
  template:
    metadata:
      labels:
        app: trading
        service: chat
      annotations:
        io.opentelemetry.discovery.logs/enabled: "true"
        instrumentation.opentelemetry.io/inject-sdk: "opentelemetry-operator-system/elastic-instrumentation"
    spec:
      containers:
        - name: chat
          env:
            - name: OTEL_SEMCONV_STABILITY_OPT_IN
              value: "gen_ai_latest_experimental"
            - name: OTEL_INSTRUMENTATION_GENAI_CAPTURE_MESSAGE_CONTENT
              value: "SPAN_AND_EVENT"
            - name: OPENAI_MODEL
              value: "mock-openai"
            - name: OPENAI_API_KEY
              value: "sk-1234"
            - name: OPENAI_BASE_URL
              value: "http://litellm-service.infra.svc.cluster.local:4000/v1"
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: "telemetry.distro.name=elastic"

            - name: OTEL_DEPLOYMENT_ENVIRONMENT
              value: $NAMESPACE 
            - name: OTEL_SERVICE_NAME
              value: "chat"

            - name: OTEL_EXPORTER_OTLP_PROTOCOL
              value: "http/protobuf"
            - name: OTEL_TRACES_EXPORTER
              value: "otlp"
            - name: OTEL_METRICS_EXPORTER
              value: "otlp"
            - name: OTEL_LOGS_EXPORTER
              value: "otlp"

          image: $REPO/chat:$COURSE
          imagePullPolicy: Always
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: trading
    service: chat
  name: chat
  namespace: $NAMESPACE
spec:
  ports:
    - name: chat
      port: 8000
      targetPort: 8000
  selector:
    app: trading
    service: chat
---
