apiVersion: v1
kind: Namespace
metadata:
  name: infra
  labels:
    name: infra
---
apiVersion: v1
data:
  datasource.yml: |-
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus.infra.svc.cluster.local:9090 
        editable: true

      - name: Elasticsearch
        type: prometheus
        access: proxy
        url: "$elasticsearch_es_endpoint/_prometheus/metrics-generic.prometheus-default"
        isDefault: true
        uid: elasticsearch-prometheus
        jsonData:
          httpMethod: GET
          httpHeaderName1: "Authorization"
          timeInterval: 15s  # Prometheus scrape interval (default: 15s)
        secureJsonData:
          httpHeaderValue1: "ApiKey $elasticsearch_api_key"
kind: ConfigMap
metadata:
  labels:
    service: grafana
  name: grafana-datasources
  namespace: infra
---
apiVersion: v1
data:
  provider.yml: |-
    apiVersion: 1
    providers:
      - name: 'Dashboards'
        folder: 'Infra'
        type: file
        options:
          path: /var/lib/grafana/dashboards
kind: ConfigMap
metadata:
  labels:
    service: grafana
  name: grafana-dashboards
  namespace: infra
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: infra
  labels:
    service: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      service: grafana
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        service: grafana
      annotations:
        io.opentelemetry.discovery.logs/enabled: "true"
    spec:
      initContainers:
        - name: init-dashboards
          image: $REPO/grafana-dashboards:$COURSE
          imagePullPolicy: Always
          command: ["sh", "-c"]
          args:
            - |
              cp /dashboards/*.json /tmp/dashboards/
          volumeMounts:
          - mountPath: /tmp/dashboards
            name: dashboard-volume
      containers:
        - env:
            - name: GF_SECURITY_ADMIN_PASSWORD
              value: "grafana"
            - name: GF_SECURITY_ADMIN_USER
              value: "admin"

            - name: GF_AUTH_DISABLE_LOGIN_FORM
              value: "true"
            - name: GF_AUTH_ANONYMOUS_ENABLED
              value: "true"
            - name: GF_AUTH_ANONYMOUS_ORG_ROLE
              value: "Admin"
            - name: GF_AUTH_ANONYMOUS_ORG_NAME
              value: "Main Org."
            - name: GF_USERS_DEFAULT_THEME
              value: "light"

          image: grafana/grafana
          name: grafana
          ports:
            - containerPort: 3000
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/grafana/dashboards
              name: dashboard-volume
            - mountPath: /etc/grafana/provisioning/datasources
              name: grafana-datasources
            - mountPath: /etc/grafana/provisioning/dashboards
              name: grafana-dashboards
      restartPolicy: Always
      volumes:
        - name: grafana-datasources
          configMap:
            name: grafana-datasources
        - name: grafana-dashboards
          configMap:
            name: grafana-dashboards     
        - name: dashboard-volume
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: grafana
  name: grafana
  namespace: infra
spec:
  ports:
    - name: "3000"
      port: 3000
      targetPort: 3000
  selector:
    service: grafana
---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: grafana
  name: grafana
  namespace: infra
spec:
  ports:
    - name: "3000"
      port: 3000
      targetPort: 3000
  type: ClusterIP
  selector:
    service: grafana
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: grafana-route
  namespace: infra
spec:
  entryPoints:
    - grafana
  routes:
    - kind: Rule
      match: PathPrefix(`/`)
      services:
        - name: grafana
          port: 3000
      middlewares:
        - name: basic-auth-middleware
          namespace: traefik
---
apiVersion: v1
data:
  prometheus.yml: |-
    global:
      scrape_interval: 15s
      scrape_timeout: 10s
      evaluation_interval: 15s
    alerting:
      alertmanagers:
      - static_configs:
        - targets: []
        scheme: http
        timeout: 10s
        api_version: v2
    scrape_configs:
      - job_name: prometheus
        honor_timestamps: true
        metrics_path: /metrics
        scheme: http
        static_configs:
        - targets:
          - router.trading-na.svc.cluster.local:9000
          - router.trading-emea.svc.cluster.local:9000
          - redis-service.infra.svc.cluster.local:9000
          labels:
            namespace: 'infra'
    remote_write:
      - url: "$elasticsearch_es_endpoint/_prometheus/api/v1/write"
        authorization:
          type: "ApiKey"
          credentials: "$elasticsearch_api_key"
kind: ConfigMap
metadata:
  labels:
    service: prometheus
  name: prom-config
  namespace: infra
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: infra
  labels:
    service: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      service: prometheus
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        service: prometheus
      annotations:
        io.opentelemetry.discovery.logs/enabled: "true"
    spec:
      containers:
        - args:
            - --config.file=/etc/prometheus/prometheus.yml
          image: prom/prometheus
          name: prometheus
          ports:
            - containerPort: 9090
              protocol: TCP
          volumeMounts:
            - mountPath: /etc/prometheus
              name: prom-config
      restartPolicy: Always
      volumes:
        - configMap:
            name: prom-config
          name: prom-config
---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: prometheus
  name: prometheus
  namespace: infra
spec:
  ports:
    - name: "9090"
      port: 9090
      targetPort: 9090
  selector:
    service: prometheus