name: com-example-kubernetes-action
enabled: true
tags:
- com-example-rca

triggers:
- type: manual
  inputs:
  - name: service_name
    type: string
    description: the name of the service
  - name: namespace
    type: string
    description: namespace the service is running in
  - name: service_action
    type: string
    description: the action to take (restart)
  - name: case_id
    type: string
    default: NOT_AVAILABLE
steps:

- name: review
  type: waitForInput
  with:
    message: |
      ## About to perform an action on a service

      **Service Name:** {{ inputs.service_name }}
      **Namespace:** {{ inputs.namespace}}
      **Requested Action:** {{ inputs.service_action}}   

      Proceed?
    schema:
      type: object
      properties:
        approved:
          type: boolean
          title: Proceed
      required: [approved]

- name: check_approval
  type: if
  condition: ${{ steps.review.output.response.approved }}
  steps:
  - name: call_remote
    type: http
    connector-id: kubernetes
    with:
      path: '/service/{{inputs.namespace}}/{{inputs.service_name}}/{{inputs.service_action}}'
      method: POST
      headers:
        Content-Type: application/json

  - name: add_comment_to_existing_case
    type: kibana.request
    with:
      method: POST
      path: /api/cases/{{ inputs.case_id }}/comments
      body:
        type: user
        owner: observability
        comment: ⚡ Attempted `{{inputs.service_action}}` of `{{inputs.service_name}}`
    on-failure:
      continue: true
