name: build-topologies
enabled: true
version: '1'
description: build topology to help with correlation and RCA
tags:
- rca
settings:
  timeout: 5m
triggers:
- type: manual
steps:

- name: get_topologies
  type: ai.agent
  create-conversation: false
  agent-id: rca
  with:
    schema:
        title: Topologies
        type: object
        additionalProperties: false
        properties:
          topologies:
            type: array
            items:
              type: object
              properties:
                system_environment:
                  type: string
                  description: the system environment
                topology:
                  type: object
                  properties:
                    edges:
                      type: array
                      items:
                        type: object
                        properties:
                          source:
                            type: string
                            description: the source service.name
                          target:
                            type: string
                            description: the destination service.name
                    nodes:
                      type: array
                      items:
                        type: object
                        properties:
                          service.name:
                            type: string
                            description: the name/id of the node
                          host.name:
                            type: string
                            description: hostname of the VM or Kubernetes node or machine on which the service is running
                          entity.type:
                            type: string
                            description: the type of entity that this node represents (you can get this from the `identify_entity_by_service_name` tool)
                          entity.function:
                            type: string
                            description: one of `service` or `database` or 'proxy'
                          k8s.namespace.name:
                            type: string
                            description: the Kubernetes namespace on which the service is running
                          language:
                            type: string
                            description: the language the service is programmed in, if known
    message: "Get system topologies from {{ 'now' | date: '%s' | minus: 3600 | date: '%Y-%m-%dT%H:%M:%SZ' }} to {{ 'now' | date: '%Y-%m-%dT%H:%M:%SZ' }}."


- name: foreach_topology
  type: foreach
  foreach: '{{ steps.get_topologies.output.structured_output.topologies }}'
  steps:
  - name: debug
    type: console
    with:
      message: "{{ foreach.item['system_environment']}}"

  - name: store_topology
    type: elasticsearch.request
    with:
      method: POST
      path: /workflow_topology/_doc
      body: '{{ foreach.item | json }}'
      headers:
        Content-Type: application/json
