o11y--course--field--elasticon-2026:
  agents:
  ai_indexes:
  aliases:
    - logs-trader.json
    - metrics-trader.json
  connectors:
  dashboards:
    - LiteLLM Observability.json
  data_views:
    - logs-trader.json
    - metrics-trader.json
  esql_datasets:
  esql_datasources:
  esql_views:
  field_definitions:
    - ai_conversation_id.json
    - system_environment.json
  ilm:
  knowledge:
  ml:
  objects:
  pipelines:
  rules:
    - apm_failure.json
  rules_eable:
  skills:
    - elastic-case-creation.json
    - elastic-esql-query-generation.json
  slos:
    - service_availability.json
    - service_latency.json
  streams:
    - logs-generic.otel-default:
      - ingest.json
  synthetics:
    - monkey_state.json
    - trade.json
  tools:
  workflows:
    com-example-rca:
      - com-example-setup.yaml
