apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubectl-pod-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubectl-pod-admin-binding
subjects:
  - kind: ServiceAccount
    name: kubectl-pod-sa
    namespace: default
roleRef:
  kind: ClusterRole
  name: cluster-admin # Use a more restrictive role in production
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: batch/v1
kind: Job
metadata:
  name: superdemo-install-$I
  namespace: default
spec:
  backoffLimit: 0 
  template:
    spec:
      serviceAccountName: kubectl-pod-sa # Binds the RBAC permissions
      containers:
        - image: us-central1-docker.pkg.dev/elastic-sa/tbekiares/install:$COURSE
          name: superdemo-install
          imagePullPolicy: Always
          env:
            - name: K3S
              value: "$K3S"
            - name: COURSE
              value: "$COURSE"
            - name: ELASTICSEARCH_URL
              value: "$ELASTICSEARCH_URL"
            - name: ELASTICSEARCH_APIKEY
              value: "$ELASTICSEARCH_APIKEY"
            - name: ACCESS_PASSWORD
              value: "$ACCESS_PASSWORD"
            - name: FLEET_URL
              value: "$FLEET_URL"
            - name: KIBANA_URL
              value: "$KIBANA_URL"
            - name: INGEST_URL
              value: "$INGEST_URL"
            - name: HTTP_AUTH
              value: "$HTTP_AUTH"
            - name: REMOTE_ENDPOINT
              value: "$REMOTE_ENDPOINT"

            - name: WINDOWS_HOST_IP
              value: "$WINDOWS_HOST_IP"
            - name: WINDOWS_HOST_USERNAME
              value: "$WINDOWS_HOST_USERNAME"
            - name: WINDOWS_HOST_PASSWORD
              value: "$WINDOWS_HOST_PASSWORD"
      restartPolicy: Never
---
