apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    providers:
      kubernetesCRD:
        allowCrossNamespace: true
    ports:
      wiki:
        port: 9010
        exposedPort: 9010
        expose:
          default: true 
      ramen:
        port: 9011
        exposedPort: 9011
        expose:
          default: true 
      grafana:
        port: 9012
        exposedPort: 9012
        expose:
          default: true 
      windows:
        port: 9013
        exposedPort: 9013
        expose:
          default: true 
      remote:
        port: 9014
        exposedPort: 9014
        expose:
          default: true 
      logstashui:
        port: 9015
        exposedPort: 9015
        expose:
          default: true 
      trading-na:
        port: 9000
        exposedPort: 9000
        expose:
          default: true 
      trading-emea:
        port: 9001
        exposedPort: 9001
        expose:
          default: true